apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: mathgo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathgo-api
  template:
    metadata:
      labels:
        app: mathgo-api
    spec:
      containers:
      - name: mathgo-api
        image: 228115104280.dkr.ecr.ap-southeast-1.amazonaws.com/mathgo:6b04b0574ef98c8715c7a5204a6e8890f88e3711
        ports:
        - containerPort: 8080