apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathgo-api-deployment
  labels:
    app: mathgo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathgo-api
  template:
    metadata:
      labels:
        app: mathgo-api
    spec:
      containers:
      - name: mathgo-api
        image: 228115104280.dkr.ecr.ap-southeast-1.amazonaws.com/mathgo:38703eee75fbe76f359e5cd875f00092f12cff23
        ports:
        - containerPort: 8080