apiVersion: apps/v1
kind: Deployment
metadata:
  name: mathgo-api-deployment
  labels:
    app: mathgo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mathgo-api
  template:
    metadata:
      labels:
        app: mathgo-api
    spec:
      containers:
      - name: mathgo-api
        image: 228115104280.dkr.ecr.ap-southeast-1.amazonaws.com/mathgo:0ebfdb3ed5702dc62181147677fc63c2770a5fff
        ports:
        - containerPort: 8080